config/routes.rb
Rails.application.routes.draw do
  resources :campaings

  resources :employees

  root 'employees#index'

end

app/models/campaing.rb
class Campaing < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaings_controller.rb
class CampaingsController < ApplicationController
  before_action :set_campaing, only: [:show, :edit, :update, :destroy]

  # GET /campaings
  # GET /campaings.json
  def index
    @campaings = Campaing.all
  end

  # GET /campaings/1
  # GET /campaings/1.json
  def show
  end

  # GET /campaings/new
  def new
    @campaing = Campaing.new
  end

  # GET /campaings/1/edit
  def edit
  end

  # POST /campaings
  # POST /campaings.json
  def create
    @campaing = Campaing.new(campaing_params)

    respond_to do |format|
      if @campaing.save
        format.html { redirect_to @campaing, notice: 'Campaing was successfully created.' }
        format.json { render :show, status: :created, location: @campaing }
      else
        format.html { render :new }
        format.json { render json: @campaing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaings/1
  # PATCH/PUT /campaings/1.json
  def update
    respond_to do |format|
      if @campaing.update(campaing_params)
        format.html { redirect_to @campaing, notice: 'Campaing was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaing }
      else
        format.html { render :edit }
        format.json { render json: @campaing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaings/1
  # DELETE /campaings/1.json
  def destroy
    @campaing.destroy
    respond_to do |format|
      format.html { redirect_to campaings_url, notice: 'Campaing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaing
      @campaing = Campaing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaing_params
      params.require(:campaing).permit(:campaingName, :campaingCode, :status)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :document, :jobDescription, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaings_helper.rb
module CampaingsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/campaings/_form.html.erb
<%= simple_form_for @campaing, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :campaingName %>
  <%= error_span(@campaing[:campaingName]) %>
  <%= f.input :campaingCode %>
  <%= error_span(@campaing[:campaingCode]) %>
  <%= f.input :status %>
  <%= error_span(@campaing[:status]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                campaings_path, :class => 'btn btn-default' %>
<% end %>

app/views/campaings/edit.html.erb
<%- model_class = Campaing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaings/index.html.erb
<%- model_class = Campaing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:campaingName) %></th>
      <th><%= model_class.human_attribute_name(:campaingCode) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @campaings.each do |campaing| %>
      <tr>
        <td><%= link_to campaing.id, campaing_path(campaing) %></td>
        <td><%= campaing.campaingName %></td>
        <td><%= campaing.campaingCode %></td>
        <td><%= campaing.status %></td>
        <td><%=l campaing.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_campaing_path(campaing), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      campaing_path(campaing),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_campaing_path,
            :class => 'btn btn-primary' %>

app/views/campaings/new.html.erb
<%- model_class = Campaing -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaings/show.html.erb
<%- model_class = Campaing -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:campaingName) %>:</strong></dt>
  <dd><%= @campaing.campaingName %></dd>
  <dt><strong><%= model_class.human_attribute_name(:campaingCode) %>:</strong></dt>
  <dd><%= @campaing.campaingCode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @campaing.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              campaings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_campaing_path(@campaing), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              campaing_path(@campaing),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@employee[:name]) %>
  <%= f.input :document %>
  <%= error_span(@employee[:document]) %>
  <%= f.input :jobDescription %>
  <%= error_span(@employee[:jobDescription]) %>
  <%= f.input :email %>
  <%= error_span(@employee[:email]) %>
  <br>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-info' %>
<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:document) %></th>
      <th><%= model_class.human_attribute_name(:jobDescription) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.id, employee_path(employee) %></td>
        <td><%= employee.name %></td>
        <td><%= employee.document %></td>
        <td><%= employee.jobDescription %></td>
        <td><%= employee.email %></td>
        <td><%=l employee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-info' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-info' %>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @employee.name %></dd>
  <dt><strinverseong><%= model_class.human_attribute_name(:document) %>:</strong></dt>
  <dd><%= @employee.document %></dd>
  <dt><strong><%= model_class.human_attribute_name(:jobDescription) %>:</strong></dt>
  <dd><%= @employee.jobDescription %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @employee.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-info'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-info' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Complarketing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head> <br><br>
<div class="container">
	<div class="row"><div class="navbar navbar-default" id="mainmenu">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Complarketing</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Active</a></li>
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left">
      <input class="form-control col-lg-8" placeholder="Search" type="text">
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div></div>
</div>



<body>

<div class="container" id="amilkar">
	<div class="row"><%= yield %> <br><br>
</div>
</div>

</body>
</html>